all: Ques2_1  Ques2_2  Ques2_3

Ques2_1: Ques2_1.c
	gcc -o Ques2_1 Ques2_1.c

Ques2_2: Ques2_2.c
	gcc -o Ques2_2 Ques2_2.c

Ques2_3: Ques2_3.c
	gcc -o Ques2_3 Ques2_3.c

clean:
	-@-rm -f Ques2_1
	-@-rm -f Ques2_2
	-@-rm -f Ques2_3